database:
  host: postgres
  port: 5432
  user: admino
  password: admino
  name: pandora_logs
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 30m

logger:
  level: info
  format: json
  output: stdout
  file:
    path: ./logs/app.log
    max_size_mb: 100
    max_backups: 7
    max_age_days: 30
    compress: true

server:
  address: "0.0.0.0:8080"
  read_timeout: 10s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 15s

metrics:
  enabled: true
  path: /metrics

tracing:
  enabled: false
  endpoint: ""

security:
  enable_tls: false
  cert_file: ""
  key_file: ""

cors:
  allowed_origins:
    - "http://localhost:63342"
  allowed_methods:
    - "*"
  allowed_headers:
    - "*"
  allow_credentials: true
